# Generated by Django 4.2.4 on 2023-08-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/user.webp', upload_to='', verbose_name='Изображение'),
        ),
    ]
