# Generated by Django 4.2.4 on 2023-08-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/', upload_to='', verbose_name='Изображение'),
        ),
    ]
