# Generated by Django 4.2.4 on 2023-08-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/user.webp', upload_to='users/', verbose_name='Изображение'),
        ),
    ]
