# Generated by Django 4.2.4 on 2023-08-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_updated_at_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
